// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sispec.Infra.Context;

namespace Sispec.Infra.Migrations
{
    [DbContext(typeof(SispecContext))]
    partial class SispecContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sispec")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Sispec.Domain.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("IdLocal");

                    b.Property<string>("Tema");

                    b.HasKey("Id");

                    b.HasIndex("IdLocal");

                    b.ToTable("Evento");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Evento");
                });

            modelBuilder.Entity("Sispec.Domain.Entities.InscritoEvento", b =>
                {
                    b.Property<int>("IdPessoa");

                    b.Property<int>("IdEvento");

                    b.HasKey("IdPessoa", "IdEvento");

                    b.HasIndex("IdEvento");

                    b.ToTable("InscritoEvento");
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacidade");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnName("contato");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("pessoa");
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Curso", b =>
                {
                    b.HasBaseType("Sispec.Domain.Entities.Evento");

                    b.Property<DateTime>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.Property<string>("FerramentasUtilizadas");

                    b.Property<int>("IdPessoa");

                    b.Property<string>("PreRequisitos");

                    b.Property<DateTime>("TempoDuracao");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Curso");

                    b.HasDiscriminator().HasValue("Curso");
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Entreterimento", b =>
                {
                    b.HasBaseType("Sispec.Domain.Entities.Evento");

                    b.Property<DateTime>("DataFim")
                        .HasColumnName("Entreterimento_DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnName("Entreterimento_DataInicio");

                    b.Property<int>("IdPessoa")
                        .HasColumnName("Entreterimento_IdPessoa");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Entreterimento");

                    b.HasDiscriminator().HasValue("Entreterimento");
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Palestra", b =>
                {
                    b.HasBaseType("Sispec.Domain.Entities.Evento");

                    b.Property<DateTime>("Data");

                    b.Property<int>("IdPessoa")
                        .HasColumnName("Palestra_IdPessoa");

                    b.Property<DateTime>("tempoDuracao");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Palestra");

                    b.HasDiscriminator().HasValue("Palestra");
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Evento", b =>
                {
                    b.HasOne("Sispec.Domain.Entities.Local", "Local")
                        .WithMany("Evento")
                        .HasForeignKey("IdLocal")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sispec.Domain.Entities.InscritoEvento", b =>
                {
                    b.HasOne("Sispec.Domain.Entities.Evento", "Evento")
                        .WithMany("Inscritos")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sispec.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Inscritos")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Curso", b =>
                {
                    b.HasOne("Sispec.Domain.Entities.Pessoa", "Orientador")
                        .WithMany("Curso")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Entreterimento", b =>
                {
                    b.HasOne("Sispec.Domain.Entities.Pessoa", "Organizador")
                        .WithMany("Entreterimento")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sispec.Domain.Entities.Palestra", b =>
                {
                    b.HasOne("Sispec.Domain.Entities.Pessoa", "Palestrante")
                        .WithMany("Palestra")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
